Toggle is nullable
strapi/buffet pull request #175
Opened 2021-01-11 10:16 UTC by ThewBear

### What does it do?

Toggle correctly show `null` value.

### Why is it needed?

Since the boolean is nullable, Toggle should display that state instead of `false`. For more information, see https://github.com/strapi/strapi/issues/9013#issuecomment-757755285

### Screenshots

![Toggle initialized as null](https://user-images.githubusercontent.com/26767607/104168387-92069380-5430-11eb-83fa-32bd9cf6454d.gif)

2021-01-12 15:35 UTC, HichamELBSI requested changes
Hello @ThewBear  Thank you for your contribution.

2021-01-12 15:35 UTC, HichamELBSI commented on packages/buffetjs-core/src/components/Toggle/index.js
> +            onChange({ target: { name, value: targetValue } });
Can you create a `handle` function for the onClick event, please? 

```js
const handleRef = ....

const handleChange = e => {
    let targetValue = e.target.checked;
    // Handle click when the state is inteterminate
    if (value === null) {
      // Select the right value depending on the mouse position
      targetValue = e.nativeEvent.offsetX >= e.target.offsetWidth / 2;
    }
    onChange({ target: { name, value: targetValue } });
};

...

<StyledToggle 
   ...
   onChange={handleChange}
/>
/>
```

2021-01-13 08:45 UTC, soupette requested changes

2021-01-13 08:45 UTC, soupette commented on docs/stories/components/Toggle.stories.js
> +  const initValue = useRef(props.initValue);
Can you use an effect here instead of a ref?


```
useEffect(() => {
    setValue(props.initValue);
  }, [props.initValue]);
```

2021-01-13 08:45 UTC, soupette commented on docs/stories/components/Toggle.stories.js
> +  if (props.initValue !== initValue.current) {
With the effect this won't be needed.

2021-01-13 08:45 UTC, soupette commented on packages/buffetjs-core/src/components/Toggle/index.js
> +  const handleRef = element => {
Can you wrap this in a `useCallback` hook to avoid the ref being computed on every render?

2021-01-13 15:38 UTC, HichamELBSI approved these changes
LGTM

2021-01-14 15:21 UTC, HichamELBSI approved these changes

2021-01-14 15:21 UTC, merged